# Generated by Django 2.2.9 on 2020-02-10 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=15)),
                ('abreviation_name', models.CharField(max_length=6)),
                ('stade_name', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_name', models.CharField(max_length=20)),
                ('date', models.DateField(verbose_name='date')),
                ('nbr_equipes', models.IntegerField(default=0)),
                ('jr_joue', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='classement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbr_point', models.IntegerField(default=0)),
                ('match_joue', models.IntegerField(default=0)),
                ('db', models.IntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentation.Club')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentation.Competition')),
            ],
        ),
    ]
