# Generated by Django 2.2.9 on 2020-02-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classement',
            name='groupe',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='club_name',
            field=models.CharField(max_length=30),
        ),
    ]
