# Generated by Django 2.2.9 on 2020-02-19 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0002_auto_20200212_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_groupe', models.CharField(max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='classement',
            name='competition',
        ),
        migrations.AlterField(
            model_name='classement',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentation.Groupe'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_match', models.DateField()),
                ('stade', models.CharField(max_length=25)),
                ('score_int', models.IntegerField(default=0)),
                ('equipe_ext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe_ext', to='presentation.Club')),
                ('equipe_int', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe_int', to='presentation.Club')),
            ],
        ),
        migrations.AddField(
            model_name='groupe',
            name='equipe',
            field=models.ManyToManyField(through='presentation.Classement', to='presentation.Club'),
        ),
    ]
