# Generated by Django 2.2.9 on 2020-02-20 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0006_auto_20200219_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_stade', models.CharField(max_length=20)),
                ('nombre_palce', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='club',
            name='stade_name',
        ),
        migrations.AlterField(
            model_name='groupe',
            name='equipe',
            field=models.ManyToManyField(through='presentation.Classement', to='presentation.Club'),
        ),
        migrations.AlterField(
            model_name='match',
            name='stade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presentation.Stade'),
        ),
        migrations.AddField(
            model_name='club',
            name='stade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='presentation.Stade'),
            preserve_default=False,
        ),
    ]
