# Generated by Django 2.2.9 on 2020-02-20 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0010_auto_20200220_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='stade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='presentation.Stade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupe',
            name='equipe',
            field=models.ManyToManyField(through='presentation.Classement', to='presentation.Club'),
        ),
    ]
