# Generated by Django 2.2.9 on 2020-02-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0013_auto_20200220_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='statu',
            field=models.CharField(choices=[('EC', 'EN_COUR'), ('FT', 'FULL_TIME'), ('RPT', 'REPORTER')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupe',
            name='equipe',
            field=models.ManyToManyField(through='presentation.Classement', to='presentation.Club'),
        ),
    ]
