# Generated by Django 2.2.9 on 2020-02-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0015_auto_20200222_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='equipe',
            field=models.ManyToManyField(through='presentation.Classement', to='presentation.Club'),
        ),
        migrations.AlterField(
            model_name='match',
            name='statu',
            field=models.CharField(choices=[('AV', 'A_VENIR'), ('EC', 'EN_COUR'), ('FT', 'FULL_TIME'), ('RPT', 'REPORTER')], default='A_VENIR', max_length=2),
        ),
    ]
