# Generated by Django 2.2.9 on 2020-02-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0018_auto_20200222_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='journee_encr',
            field=models.CharField(choices=[('PR', '1er'), ('SD', '2sd'), ('TR', '3eme'), ('QT', '4eme')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupe',
            name='equipe',
            field=models.ManyToManyField(through='presentation.Classement', to='presentation.Club'),
        ),
    ]
