# Generated by Django 2.2.9 on 2020-02-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0019_auto_20200222_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='equipe',
            field=models.ManyToManyField(through='presentation.Classement', to='presentation.Club'),
        ),
    ]
